channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0
- pip:
  - mlflow==2.22.0
  - astunparse==1.6.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - torch==2.5.1
  - tqdm==4.67.1
name: mlflow-env
